name: Publish Packages

on:
  release:
    types: [published]
  workflow_call:

jobs:
  build:
    # Skip if it's not running in the `serverlessworkflow/sdk-net` repo
    if: github.repository == 'serverlessworkflow/sdk-net'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore "./ServerlessWorkflow.Sdk.sln"
    - name: Build
      run: dotnet build "./ServerlessWorkflow.Sdk.sln" --configuration Release --no-restore
    - name: Push
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/ServerlessWorkflow.Sdk/ServerlessWorkflow.Sdk.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
        
